### ISSUE TITLE
README nitpick: checksum

### ISSUE THREAD

**Issue by secworks** [system-transparency/stfe#1]
Some minor nits on the README

The first bullet in the first list: "A checksum that covers something opaque, e.g., an executable binary."

(1) "Covers" is not a well defined word (I think) when it comes to checcksums. I would suggest "represents".
(2) "something opaque" -> "a data item of opaque type"?
(3) "e.g., an executable binary". The twxt before the bullet gives examples that are not executable binaries. This seems like a surprising limitation.

**Comment by rgdd** [comment]
Thanks for reporting these nits! Please take a look if you think they are addressed now.

**Comment by secworks** [comment]
Yes, much better!.
