### ISSUE TITLE
README: Nitpick signature

### ISSUE THREAD

**Issue by secworks** [system-transparency/stfe#2]
First bullet list:
"A signature that covers checksum and identifier using the submitter's secret signing key."

(1) I think it would be good to clarify that it is a cryptographic signature, to distinguish from the checksum
(2) The word "covers" is a bit ambiguous. I suggest you clarify what it means in this context.

**Comment by rgdd** [comment]
Thanks (again) for reporting these nits! I replaced the word "covers" and then tried to emphasize both of your points in the first sentence of the following paragraph. Let me know what you think of the proposed changes.

**Comment by secworks** [comment]
Looks good, thanks!
