### ISSUE TITLE
HTTP status 405, no Allow header

### ISSUE THREAD

**Issue by ln5** [system-transparency/stfe#5]
When using HTTP GET for a POST endpoint or vice versa, HTTP status code 405 is returned by the server. According to RFC2616 an `Allow` header MUST be included in the response.

**Comment by ln5** [comment]
```
10.4.6 405 Method Not Allowed

   The method specified in the Request-Line is not allowed for the
   resource identified by the Request-URI. The response MUST include an
   Allow header containing a list of valid methods for the requested
   resource.
```

**Comment by rgdd** [comment]
Relevant place to start looking:

https://github.com/system-transparency/stfe/blob/60d6b27b964d149f51bca5d1990698700e280051/pkg/instance/instance.go#L80

**Comment by rgdd** [comment]
repository moved to github.com/sigsum
