### ISSUE TITLE
Server configuration

### ISSUE THREAD

**Issue by ln5** [system-transparency/stfe#6]
All server configuration is done through "go flags", ie command arguments to the program. This is good for configuration settings which last through the lifetime of an invocation of a log instance, ie from launch to Ctrl-C. Examples: `--http_endpoint`, `--key`. It's less good for settings that change over time. Example: `--witnesses`.

Reading a configuration file at start and when receiving, say, SIGHUP, is an alternative.

Implementing a "control port", typically a TCP endpoint, where an administrator can "program" the log instance is another alternative. Such an interface can also be used for diagnostics.

**Comment by rgdd** [comment]
repository moved to github.com/sigsum
